### PR TITLE
Make it visible with OS dark theme.

### PR DESCRIPTION
**Pull request by hawkeye116477**
On Linux with dark theme turned on, text is black and background is also black, so options are invisible.
So as a fix I set background as white, but the other way is also possible, you can follow dark/light OS theme with `color: -moz-DialogText; background-color: -moz-Dialog;`.

### CODE REVIEW

**Comment by zakius** [comment]
Judging by docs browser theme should be injected into the pop-up (by the `"browser_style": true,` manifest field), but that might be not true for 56 yet. Thanks for pointing this out, I'll opt for the latter option.

**Comment by happysmash27** [comment]
I just made my own fancy theme for Polly, not realising this already existed... 

I guess I will make another pull request and we can use whichever one is best?

**Comment by happysmash27** [comment]
Or... maybe it would be best to combine them. Mine has a header and a bunch of other tweaks to look nicer, but the colour scheme is a bit crazy, with a pink header and blue body, in order to fit about equally in both dark and light themes, as I didn't realise there was a method to just use the system theme.

**Comment by zakius** [comment]
I'll be accepting @happysmash27 's PR as it solves the same issue and improves the rough interface a bit so I'm closing this one. Thanks for your contribution nonetheless

**Pull request closed without merging**
